spec/definitions/GatewayAccount.yaml
for example:
```  
"restriction":{  
"op":"and",
"conditions":[  
{  
"op":"not",
"condition":{  
"op":"in-list",
"path":"/transaction/paymentCard/bin",
"listId":"bad-bin-list",
}
},
{  
"op":"not",
"condition":{  
"op":"in-list",
"path":"/transaction/customerId",
"listId":"bad-customer-list",
}
},
{  
"op":"not",
"condition":{  
"op":"in-list",
"path":"/transaction/paymentCard/bankCountry",
"listId":"bad-country-list",
}
}
]
}
```
=> Gateway account list restrictions

spec/definitions/EmailNotifications/EmailNotification.yaml
Remove wrong events:
- `subscription-created`
- `payment-declined`
=> Remove wrong email notification events

spec/definitions/Blacklist.yaml
Reverts Rebilly/RebillyUserAPI#47
=> Revert "Add missed TTL to blacklist definition"

spec/definitions/GatewayAccountConfig/Cardknox.yaml
Please also see
https://github.com/Rebilly/api-standards/pull/3
=> Add Cardknox

spec/definitions/Placeholders/SubscriptionPlaceholders.yaml
Add `initialInvoice` relation to `Subscription` resource.
=> Adjust subscription placeholders

spec/definitions/Note.yaml
Remove unsupported Note resource types.
=> Remove unsupported Note resource types

spec/definitions/EmailNotifications/EmailNotification.yaml
Add email notifications `attachInvoice` attribute.
=> Add email notifications attachInvoice attribute

spec/definitions/Contact.yaml, spec/definitions/Contact/ContactObject.yaml, spec/definitions/Coupon/CouponRedemption.yaml, spec/definitions/CustomField.yaml
This PR fixes some merge conflicts.
=> Fix merge conflicts

spec/swagger.yaml
Reverts Rebilly/RebillyUserAPI#137
=> Revert "Add Customers tag"

spec/definitions/Organization.yaml, spec/paths/api-keys@{id}.yaml, spec/paths/custom-events@{id}.yaml, spec/paths/organizations.yaml, spec/paths/organizations@{id}.yaml, spec/paths/profile.yaml, spec/paths/users@{id}.yaml
Adjusted references so that corresponding fields will not be ignored.
=> Fix references

spec/components/schemas/CheckoutPage.yaml, spec/components/schemas/CheckoutPage/FieldConfig.yaml, spec/components/schemas/CheckoutPage/Section.yaml, spec/components/schemas/CheckoutPage/Style.yaml, spec/components/schemas/CheckoutPage/Taxes.yaml, spec/openapi.yaml, spec/paths/checkout-pages.yaml, spec/paths/checkout-pages@{id}.yaml
I think we need  to fix our PHP SDK for CheckoutPage : 
```
uriPath  => urlPathSegment
isActive => status 
redirectUrl + redirectTimeout  => redirect
allowCustomCustomerId  => isCustomCustomerIdAllowed
```
and then change php examples here
=> Update definition of checkout pages

spec/components/schemas/GatewayAccountConfig/BitPay.yaml
Provides a BitPay Gateway config definition
See: https://jira.ilabsinc.com/browse/GWY-10874
=> Add BitPay

spec/components/schemas/GlobalWebhookEventType.yaml
=> Add customer-merged global webhook event

spec/components/schemas/GatewayAccountConfig/Neteller.yaml
=> Add Neteller gateway config

spec/paths/tracking@webhooks@{id}@resend.yaml
This PR adds API endpoint that allows to resend webhook
=> Add resend webhook API endpoint

spec/components/schemas/GatewayAccountConfig/INOVAPAY.yaml
This PR will add API spec for INOVAPAY
=> Add INOVAPAY

spec/components/schemas/Method.yaml
This PR will remove discrepancy in RebillyApi and RebillyUserApi payment methods list
=> Sync payment methods with RebillyApi spec methods

spec/components/schemas/Method.yaml
This PR will add payment methods for upcoming INOVAPAY gateway adapter
=> Add INOVAPAY payment methods

spec/components/schemas/GatewayAccount.yaml, spec/paths/gateway-accounts@{id}@close.yaml
Add `closed` status to Gateway Accounts. Also add the `close` endpoint.
=> Add closed status and endpoint to Gateway Accounts

spec/components/schemas/GatewayAccount.yaml
=> Fix approval rate ttl

spec/components/requestBodies/Segment.yaml, spec/components/schemas/Segment.yaml, spec/components/schemas/Segments/PatchSegment.yaml, spec/components/schemas/Segments/Segment.yaml, spec/openapi.yaml, spec/paths/grid-segments.yaml, spec/paths/grid-segments@{id}.yaml
Add endpoints for Segments API
=> Add Segment endpoints

spec/paths/grid-segments@{id}.yaml
Add the `PUT` endpoint to Segments
=> Add PUT endpoint to Segments

spec/components/schemas/GatewayAccountConfig/IpayOptions.yaml
https://jira.ilabsinc.com/browse/GWY-12575
=> Remove Ipay Options as required

spec/components/schemas/GatewayAccountConfig/Onlineueberweisen.yaml
Without this format field looks confusing
=> Fix Onlineueberweisen apiKey field format

spec/components/schemas/GatewayAccountConfig/iCanPay.yaml
=> Add iCanPay

spec/components/schemas/Segments/PatchSegment.yaml, spec/components/schemas/Segments/Segment.yaml
Add `isStarred` boolean field to Segment PATCH request and Segment response schema.
=> Add isStarred field to PATCH Segment request and schema

spec/components/schemas/Acl.yaml, spec/components/schemas/ApiKey.yaml, spec/components/schemas/ApiKeyScope.yaml
Add ApiKey.Acl
Deprecate ApiKey.Permissions
=> Add ApiKey.Acl

spec/components/schemas/GatewayAccountConfig/Onlineueberweisen.yaml
This reverts commit e31f548287a4e72216f04d8f20b2282a5ff934b7.
=> Revert "Add delay back (#339)"

spec/code_samples/PHP/checkout-pages/post.php, spec/code_samples/PHP/checkout-pages@{id}/put.php
https://github.com/Rebilly/rebilly-php/pull/384
=> Change php examples according the API definitions and php-sdk

openapi/components/schemas/GlobalWebhookEventType.yaml
Add `kyc-document-reviewed` to the Webhook events list.
=> Add kyc-document-reviewed Webhook event

openapi/components/schemas/GatewayAccount.yaml, openapi/components/schemas/GatewayAccountConfig/Sofort.yaml
Should we actually add it as a new payment method too?
=> Add Sofort gateway

openapi/components/schemas/GatewayAccountConfig/WorldlineAtosFrankfurt.yaml, openapi/components/schemas/Gateways/MpiName.yaml, openapi/components/schemas/Mpi/ThreeDSecureIOMpi.yaml, openapi/components/schemas/Mpi/WorldlineAtosFrankfurtMpis/WorldlineAtosFrankfurtMpi.yaml, openapi/components/schemas/Mpi/WorldlineAtosFrankfurtMpis/WorldlineAtosFrankfurtMpis.yaml
https://jira.ilabsinc.com/browse/GWY-15241
=> Add wordline 3ds integration

openapi/components/schemas/GatewayAccountConfig/Coppr.yaml
Add rebilly publishable key setting
=> Update Coppr gateway account config
